### ISSUE TITLE
:rotating_light: Profile & Notification error!

### ISSUE THREAD

**Issue by marissaverdonck** [marissaverdonck/InterMatching#26]
Hi guys,

something is wrong with the notifications and profile page, see the images below.

<img width="917" alt="Schermafbeelding 2019-06-12 om 20 49 52" src="https://user-images.githubusercontent.com/43657951/59378165-fbee2100-8d53-11e9-8198-63f71e225080.png">
<img width="867" alt="Schermafbeelding 2019-06-12 om 20 49 44" src="https://user-images.githubusercontent.com/43657951/59378167-fc86b780-8d53-11e9-8a09-8c5e2ad2a093.png">

**Comment by Wiebsonice** [comment]
Fixed in Pull request #41
